### ISSUE TITLE
Error with injectThemeJS.

### ISSUE THREAD

**Issue by linuxmobile** [MichaelPachec0/spicetify-nix#1]
` error: The option `home-manager.users.linuxmobile.programs.spicetify.theme.injectThemeJS' is used but not defined.`

config:

```nix
{
  inputs,
  pkgs,
  ...
}: {
  # themable spotify
  programs.spicetify = let
    spicePkgs = inputs.spicetify-nix.packages.${pkgs.system}.default;
  in {
    enable = true;
    injectCss = true;
    replaceColors = true;
    overwriteAssets = true;
    sidebarConfig = true;
    enabledCustomApps = with spicePkgs.apps; [lyrics-plus new-releases];
    theme = spicePkgs.themes.Onepunch;
    colorScheme = "gruvbox";
    enabledExtensions = with spicePkgs.extensions; [
      hidePodcasts
      shuffle
      adblock
      playlistIcons
      lastfm
      genre
      historyShortcut
      bookmark
      fullAlbumDate
      groupSession
      popupLyrics
    ];
  };
}
```

**Comment by MichaelPachec0** [comment]
For now I have removed that option so the flake should work now. Will later try and debug my implementation of the option.

If for some reason the module does not work even after updating the flake input, reopen.

**Comment by linuxmobile** [comment]
> For now I have removed that option so the flake should work now. Will later try and debug my implementation of the

Ready, working perfectly. **Thanks for updating**. The argus one is slightly outdated.
